version: '3.7'

services:
  mariadb:
    build : ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql/
    networks:
      - back_net
    environment:
        DB_ROOT: "${DB_ROOT}"
        DB_PASS_ROOT: "${DB_PASS_ROOT}"
        DB_USER: "${DB_USER}"
        DB_PASS_USER: "${DB_PASS_USER}"
        DB_NAME: "${DB_NAME}"
    ports:
      - "3306:3306"

  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/
    ports:
      - "9000:9000"
    environment:
        - WP_DB_NAME=${WP_DB_NAME}
        - WP_DB_USER=${WP_DB_USER}
        - WP_DB_PASSWORD=${WP_DB_PASSWORD}
        - DOMAIN_NAME=${DOMAIN_NAME}
        - WP_TITLE=${WP_TITLE}
        - WP_ADMIN=${WP_ADMIN}
        - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
        - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
        - WP_USER=${WP_USER}
        - WP_PASSWORD=${WP_PASSWORD}
    restart: always
    env_file:
      - .env
    networks:
      - back_net
    volumes:
      - wp:/var/www/html/

  nginx:
    depends_on:
      - wordpress   
    image: nginx
    container_name: nginx
    build: ./requirements/nginx/
    ports:
    - "443:443"
    networks:
      - back_net
    restart: always
    env_file:
      - .env
    volumes:
       - wp:/var/www/html/

networks:
  back_net:
   driver: bridge

volumes:
  wp:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/gabriel/Projetos/Inception/4attemp/srcs/data/wordpress/
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/gabriel/Projetos/Inception/4attemp/srcs/data/db/